modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/bernie-g/geckolib/issues"
license="MIT"
[[mods]]
modId="geckolib"
version="${file.jarVersion}"
displayName="GeckoLib 4"
displayURL="http://geckolib.com/"
logoFile="geckolib.png" 
credits="Gecko, Eliot, AzureDoom, DerToaster, Tslat, Witixin"
authors="Gecko, Eliot, AzureDoom, Chappie, DerToaster, Tslat, Witixin"
description='''
GeckoLib is an animation engine for Minecraft Mods, with support for complex 3D keyframe-based animations, 30+ easings, concurrent animation support, sound and particle keyframes, event keyframes, and more.
'''
[[dependencies.geckolib]]
    modId="forge"
    mandatory=true 
    versionRange="[45.0.8,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.geckolib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4, 1.20)"
    ordering="NONE"
    side="BOTH"
